name: ci
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.5.0
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "grpc"
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "grpc"
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main'