name: buf-pull
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.5.0
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "grpc"
      # TODO: Need to investigate buf docs
      # on how to use this properly if we need to update
      # protobufs regularly?
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "grpc"
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main'